### ISSUE TITLE
Tests fail (if Test::Differences::Color is installed?)

### ISSUE THREAD

**Issue by eserte** [hoelzro/devel-trace-syscall#17]
Some of my smoker systems report the failure:

```
Cannot replace non-existent sub (Test::Builder::_print_to_fh) at /home/cpansand/.cpan/build/2016080721/Test-Differences-Color-0.06-1/blib/lib/Test/Differences/Color.pm line 87.
# Looks like your test exited with 255 just after 1.
t/run_tests.t ... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 19/20 subtests 
```

It seems that this only happens if Test::Differences::Color is installed.

**Comment by eserte** [comment]
... and also Test2 has to be installed.

**Comment by hoelzro** [comment]
From what I can tell, I think this is a problem with `Test::Differences::Color` - I'll remove my usage of that module until it gets fixed, though.
